language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade tox-travis
script:
  - tox
# https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email:
    on_success: never
    on_failure: always
