language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# https://github.com/travis-ci/travis-ci/issues/9815#issue-336465122
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -e .[tests]
script:
  - pytest
# https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email:
    on_success: never
    on_failure: always
